import type { Client, Invoice, Project } from "@/types";
import { repo } from "@/data/repo";

const money = (amount: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(amount);
const text = (value?: string) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" })[character] ?? character);

/** Opens a clean A4 print sheet. The browser's Print dialog can also save it as a PDF. */
export function printTaxInvoice(invoice: Invoice, project?: Project, client?: Client | null) {
  const seller = repo.sellerProfile();
  const popup = window.open("", "_blank");
  if (!popup) return false;
  try { popup.opener = null; } catch { /* Browser may restrict opener access. */ }
  const taxRows = invoice.taxMode === "IGST"
    ? `<tr><td colspan="5" class="right">IGST @ 18%</td><td class="right">${money(invoice.igst)}</td></tr>`
    : `<tr><td colspan="5" class="right">CGST @ 9%</td><td class="right">${money(invoice.cgst)}</td></tr><tr><td colspan="5" class="right">SGST @ 9%</td><td class="right">${money(invoice.sgst)}</td></tr>`;
  popup.document.write(`<!doctype html><html><head><title>${text(invoice.number)}</title><style>
    @page{size:A4;margin:12mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#171717;font-size:12px;line-height:1.35;margin:0}.warning{background:#fff3cd;border:1px solid #e5c970;padding:8px;margin-bottom:10px;font-weight:700}.top{display:flex;justify-content:space-between;border:1px solid #222;padding:12px}.brand{font-size:22px;font-weight:800;color:#d71939}.muted{color:#555}.title{font-size:18px;font-weight:800;text-align:right}.grid{display:grid;grid-template-columns:1fr 1fr;border:1px solid #222;border-top:0}.box{padding:10px;min-height:92px}.box+ .box{border-left:1px solid #222}.label{font-size:10px;font-weight:700;text-transform:uppercase;color:#555;letter-spacing:.04em}.value{font-weight:700;margin-top:4px}table{border-collapse:collapse;width:100%;margin-top:0}th,td{border:1px solid #222;padding:7px;vertical-align:top}th{background:#f3f3f3;font-size:10px;text-transform:uppercase}.right{text-align:right}.total{font-size:14px;font-weight:800}.foot{margin-top:12px;display:flex;justify-content:space-between;gap:20px}.signature{width:220px;text-align:center;border-top:1px solid #222;padding-top:5px;margin-top:42px}.note{font-size:10px;color:#555}@media print{.no-print{display:none}}</style></head><body>
  ${!seller.gstin ? '<div class="warning">PROVISIONAL TAX INVOICE — Complete Kurchi’s legal seller profile before using this as a statutory invoice.</div>' : ""}
  <section class="top"><div><div class="brand">kurchi</div><div class="muted">Irresistibly Yours</div><div class="value">${text(seller.legalName || "Kurchi Projects")}</div><div>${text(seller.address)}</div><div>GSTIN: ${text(seller.gstin || "Pending")} · PAN: ${text(seller.pan || "Pending")}</div></div><div><div class="title">TAX INVOICE</div><div class="right"><b>Invoice No.</b> ${text(invoice.number)}<br><b>Date</b> ${new Date(invoice.issuedAt).toLocaleDateString("en-IN")}<br><b>Due date</b> ${new Date(invoice.dueDate).toLocaleDateString("en-IN")}</div></div></section>
  <section class="grid"><div class="box"><div class="label">Bill to</div><div class="value">${text(client?.name || "Ola Electric Mobility Ltd")}</div><div>${text(client?.billingAddress || "Billing address to be configured")}</div><div>GSTIN: ${text(client?.gstin || "Pending")}</div><div>Contact: ${text(client?.contactName || "Pending")} · ${text(client?.contactPhone || "Pending")}</div><div>Email: ${text(client?.contactEmail || "Pending")}</div></div><div class="box"><div class="label">Ship to</div><div class="value">${text(project?.name || "Showroom")}</div><div>${text(project?.site.address)}, ${text(project?.site.city)} — ${text(project?.site.pincode)}</div><div>Showroom GSTIN: ${text(project?.site.gstin || "Pending")}</div><div>Site contact: ${text(project?.site.contactName || "Pending")} · ${text(project?.site.contactPhone || "Pending")}</div><div>Place of supply: ${text(invoice.placeOfSupplyState)}</div></div></section>
  <table><thead><tr><th>#</th><th>Description of goods / service</th><th>HSN/SAC</th><th class="right">Qty</th><th class="right">Rate</th><th class="right">Amount</th></tr></thead><tbody>${invoice.lines.map((line,index)=>`<tr><td>${index+1}</td><td>${text(line.description)}</td><td>${text(line.hsn)}</td><td class="right">${line.qty}</td><td class="right">${money(line.rate)}</td><td class="right">${money(line.taxableValue)}</td></tr>`).join("")}<tr><td colspan="5" class="right">Taxable value</td><td class="right">${money(invoice.taxableValue)}</td></tr>${taxRows}<tr><td colspan="5" class="right total">Invoice total</td><td class="right total">${money(invoice.total)}</td></tr>${invoice.retentionAmount ? `<tr><td colspan="5" class="right">Retention</td><td class="right">−${money(invoice.retentionAmount)}</td></tr>` : ""}<tr><td colspan="5" class="right total">Net payable</td><td class="right total">${money(invoice.netPayable)}</td></tr></tbody></table>
  <section class="foot"><div class="note">This is a computer-generated document.<br>Invoice is linked to ${invoice.challanIds.length ? `delivery challan(s): ${invoice.challanIds.join(", ")}` : "the approved showroom scope"}.<br>Tax mode: ${invoice.taxMode === "IGST" ? "IGST" : "CGST + SGST"}.</div><div class="signature">Authorised signatory<br>For Kurchi Projects</div></section>
  <script>window.onload=()=>window.print()</script></body></html>`);
  popup.document.close();
  return true;
}
