import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, ArrowRight, Check, CircleDollarSign, FileText, MapPin, MessageCircle, PackageCheck, Wrench } from "lucide-react";
import { useAuth } from "@/features/auth/AuthContext";
import { repo } from "@/data/repo";
import { useDb } from "@/data/store";
import * as act from "@/data/actions";
import { useAction } from "@/lib/useAction";
import { EmptyState } from "@/components/app/Shell";
import type { OperationalStatus } from "@/types";

const JOURNEY: Array<{ key: OperationalStatus; label: string; note: string }> = [
  { key: "ADVANCE_PENDING", label: "Advance", note: "Payment confirmation" }, { key: "PRODUCTION", label: "Making", note: "In production" }, { key: "LOGISTICS", label: "Moving", note: "On the way" }, { key: "DELIVERED", label: "At site", note: "Received at location" }, { key: "INSTALLATION", label: "Installing", note: "Fitting in progress" }, { key: "COMPLETED", label: "Done", note: "Ready to close" },
];

export default function ProjectJourneyPage({ home, classic }: { home: string; classic: string }) {
  useDb();
  const { projectId = "" } = useParams();
  const { user } = useAuth();
  const run = useAction();
  const [message, setMessage] = useState("");
  const project = repo.projectById(user, projectId);
  if (!user || !project) return <EmptyState title="This showroom is not available" hint="It may belong to another workspace." />;
  const stage = project.operationalStatus ?? ((project.advanceReceivedPct ?? 0) < (project.advanceRequiredPct ?? 0) ? "ADVANCE_PENDING" : "PRODUCTION");
  const index = JOURNEY.findIndex((item) => item.key === stage);
  const items = repo.itemsRaw(project.id);
  const installed = items.filter((item) => ["INSTALLED", "HANDED_OVER"].includes(item.status)).length;
  const issueCount = repo.tickets(project.id).filter((item) => item.status !== "RESOLVED").length;
  const next = JOURNEY[Math.min(index + 1, JOURNEY.length - 1)];
  const canMove = user.role === "ADMIN" && index < JOURNEY.length - 1;
  const fieldLink = `/site/${project.id}?tab=${stage === "DELIVERED" ? "receive" : "install"}`;
  const recordsLink = classic.replace(":projectId", project.id);
  const comments = repo.comments(project.id);
  const documents = repo.documents(project.id);
  const activity = repo.audit(80).filter((entry) => entry.entity.includes(project.id)).slice(0, 4);
  const waitingForAdmin = Boolean(project.olaSubmittedAt && !project.adminAcceptedAt);
  return <>
    <Link to={home} className="mb-5 inline-flex items-center gap-1.5 text-sm font-bold text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Back to all showrooms</Link>
    <section className="rounded-[2rem] bg-rail p-6 text-rail-foreground sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-rail-muted">{waitingForAdmin ? "New showroom request" : "Showroom journey"}</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-extrabold">{project.name}</h1><p className="mt-2 flex items-center gap-1.5 text-sm text-rail-muted"><MapPin className="h-4 w-4" /> {project.site.address}, {project.site.city} · {project.site.gstin ? `GSTIN ${project.site.gstin}` : "GSTIN pending"}</p></div><span className="rounded-full bg-white/10 px-4 py-2 text-sm font-bold">{waitingForAdmin ? "Waiting for Kurchi review" : JOURNEY[index].label}</span></div>{waitingForAdmin ? <div className="mt-7 rounded-2xl bg-white/10 p-4 text-sm leading-relaxed text-rail-muted">Ola has submitted this location and franchisee owner. Kurchi Admin will verify the details, accept the request, and then prepare the BOQ.</div> : <div className="mt-8 grid gap-2 md:grid-cols-6">{JOURNEY.map((item, itemIndex) => <div key={item.key} className={`rounded-2xl p-3 ${itemIndex < index ? "bg-primary/20" : itemIndex === index ? "bg-primary text-primary-foreground" : "bg-white/5 text-rail-muted"}`}><div className="flex items-center justify-between"><p className="text-sm font-extrabold">{item.label}</p>{itemIndex < index && <Check className="h-4 w-4" />}</div><p className="mt-1 text-[11px] opacity-75">{item.note}</p></div>)}</div>}</section>
    <section className="mt-5 grid gap-3 md:grid-cols-3"><div className="rounded-3xl border bg-card p-5"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Advance received</p><p className="mt-3 text-3xl font-extrabold">{project.advanceReceivedPct ?? 0}%</p><p className="mt-1 text-sm text-muted-foreground">of {project.advanceRequiredPct ?? 0}% required</p></div><div className="rounded-3xl border bg-card p-5"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Items fitted</p><p className="mt-3 text-3xl font-extrabold">{installed} <span className="text-base text-muted-foreground">/ {items.length}</span></p><p className="mt-1 text-sm text-muted-foreground">site installation progress</p></div><div className="rounded-3xl border bg-card p-5"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Open issues</p><p className="mt-3 text-3xl font-extrabold">{issueCount}</p><p className="mt-1 text-sm text-muted-foreground">reported for this showroom</p></div></section>
    <section className="mt-5 rounded-3xl border bg-card p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[.15em] text-primary">What happens next</p><h2 className="mt-2 text-2xl font-extrabold">{waitingForAdmin ? "Kurchi needs to accept this showroom." : index === JOURNEY.length - 1 ? "This showroom is ready to close." : `${next.label} is the next step.`}</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">{waitingForAdmin ? "Once Kurchi accepts it, the team will prepare the BOQ for the franchisee owner to select and approve." : stage === "ADVANCE_PENDING" ? "Confirm the planned advance before Kurchi starts production." : stage === "DELIVERED" ? "The installation team has 48 hours to begin fitting after site delivery." : "Use the action below to keep the journey moving."}</p><div className="mt-5 flex flex-wrap gap-2">{waitingForAdmin && user.role === "ADMIN" && <button type="button" onClick={() => run(() => act.acceptOlaShowroom(user, project.id), "Showroom accepted", "You can now prepare the BOQ and start Kurchi's work.")} className="inline-flex min-h-12 items-center gap-2 rounded-2xl bg-primary px-5 text-sm font-extrabold text-primary-foreground">Accept showroom <ArrowRight className="h-4 w-4" /></button>}{canMove && !waitingForAdmin && <button type="button" onClick={() => run(() => act.setOperationalStatus(user, project.id, next.key), `Moved to ${next.label}`)} className="inline-flex min-h-12 items-center gap-2 rounded-2xl bg-primary px-5 text-sm font-extrabold text-primary-foreground">Move to {next.label} <ArrowRight className="h-4 w-4" /></button>}{user.role === "INSTALLATION" && <Link to={fieldLink} className="inline-flex min-h-12 items-center gap-2 rounded-2xl bg-primary px-5 text-sm font-extrabold text-primary-foreground"><Wrench className="h-4 w-4" /> Start site work</Link>}{user.role === "ACCOUNTS" && <Link to="/accounts/cost-centres" className="inline-flex min-h-12 items-center gap-2 rounded-2xl bg-primary px-5 text-sm font-extrabold text-primary-foreground"><CircleDollarSign className="h-4 w-4" /> Add project cost</Link>}{user.role === "CLIENT" && <Link to="/portal/approvals" className="inline-flex min-h-12 items-center gap-2 rounded-2xl bg-primary px-5 text-sm font-extrabold text-primary-foreground"><PackageCheck className="h-4 w-4" /> See project updates</Link>}<Link to={recordsLink} className="inline-flex min-h-12 items-center gap-2 rounded-2xl border px-5 text-sm font-bold">Open detailed records</Link></div></section>
    <section className="mt-5 grid gap-4 lg:grid-cols-3"><article className="rounded-3xl border bg-card p-5"><div className="flex items-center gap-2"><MessageCircle className="h-5 w-5 text-primary"/><h2 className="font-extrabold">Team conversation</h2></div><p className="mt-1 text-sm text-muted-foreground">Ask Admin, Installation, Ola or the franchisee about this showroom.</p><div className="mt-4 space-y-3">{comments.slice(0, 2).map((comment) => <div key={comment.id} className="rounded-2xl bg-muted/60 p-3"><p className="text-sm font-bold">{comment.byName}</p><p className="mt-1 text-sm">{comment.body}</p></div>)}{comments.length === 0 && <p className="rounded-2xl bg-muted/60 p-3 text-sm text-muted-foreground">No messages yet. Start the conversation below.</p>}</div><form onSubmit={(event) => { event.preventDefault(); const done = run(() => act.addComment(user, project.id, message), "Message sent"); if (done) setMessage(""); }} className="mt-4 flex gap-2"><input value={message} onChange={(event) => setMessage(event.target.value)} required placeholder="Write an update or question" className="min-h-11 min-w-0 flex-1 rounded-xl border bg-background px-3 text-sm"/><button className="rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">Send</button></form></article><article className="rounded-3xl border bg-card p-5"><h2 className="font-extrabold">Latest activity</h2><div className="mt-4 space-y-3">{activity.length ? activity.map((entry) => <div key={entry.id} className="border-l-2 border-primary/30 pl-3"><p className="text-sm font-bold">{entry.detail}</p><p className="mt-1 text-xs text-muted-foreground">{entry.actorName} · {new Date(entry.at).toLocaleDateString("en-IN")}</p></div>) : <p className="text-sm text-muted-foreground">Activity will appear when the showroom is updated.</p>}</div></article><article className="rounded-3xl border bg-card p-5"><FileText className="h-5 w-5 text-primary"/><h2 className="mt-3 font-extrabold">Project documents</h2><p className="mt-2 text-3xl font-extrabold">{documents.length}</p><p className="mt-1 text-sm text-muted-foreground">BOQ, drawings, challans, invoices and handover files.</p>{user.role === "ADMIN" && <Link to={`/admin/tools?tab=documents&project=${project.id}`} className="mt-5 inline-flex text-sm font-bold text-primary">Open document vault <ArrowRight className="ml-1 h-4 w-4"/></Link>}</article></section>
  </>;
}
