import { Link } from "react-router-dom";
import { ArrowRight, CheckCircle2, Clock3, FileText, IndianRupee, Receipt, WalletCards } from "lucide-react";
import { useAuth } from "@/features/auth/AuthContext";
import { repo, receivablesAgeing } from "@/data/repo";
import { useDb } from "@/data/store";
import { formatCompactINR } from "@/lib/money";
import { formatINR } from "@/lib/money";
import * as act from "@/data/actions";
import { useAction } from "@/lib/useAction";
import { printTaxInvoice } from "@/lib/printInvoice";

export default function AccountsHomePage() {
  useDb();
  const { user } = useAuth();
  const run = useAction();
  const projects = repo.projects(user);
  const invoices = repo.invoices();
  const ageing = receivablesAgeing(user);
  const outstanding = Object.values(ageing).reduce((sum, amount) => sum + amount, 0);
  const ready = repo.consignments().filter((item) => item.status === "READY");
  const shipmentBilling = repo.consignments().filter((item) => item.status === "READY" && item.rtsCheckedAt);
  const paymentChecks = projects.filter((project) => project.initialPayment?.status === "PENDING_VERIFICATION");
  return <>
    <section className="mb-7 rounded-[2rem] bg-rail p-6 text-rail-foreground sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-rail-muted">Kurchi finance desk</p><h1 className="mt-3 text-3xl font-extrabold">Keep each showroom financially ready.</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-rail-muted">Create documents, record project spend and close each showroom without losing track of a rupee.</p></section>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Payment checks" value={paymentChecks.length} note="new Ola payments to verify" /><Metric label="To collect" value={formatCompactINR(outstanding)} note={`${invoices.filter((invoice) => invoice.status !== "PAID").length} open invoices`} /><Metric label="Ready to move" value={ready.length} note="deliveries needing documents" /><Metric label="This month" value={formatCompactINR(repo.costEntries().reduce((sum, entry) => sum + entry.amount, 0))} note="recorded project spending" /></section>
    {paymentChecks.length > 0 && <section className="mt-7 rounded-3xl border-2 border-primary/20 bg-card p-5 sm:p-6"><div className="flex items-center gap-2"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-primary/10 text-primary"><Clock3 className="h-5 w-5"/></span><div><p className="eyebrow">First step</p><h2 className="text-xl font-extrabold">Verify Ola payments</h2></div></div><p className="mt-3 text-sm text-muted-foreground">Once you confirm the UTR and amount, the project automatically reaches Kurchi Admin.</p><div className="mt-4 space-y-3">{paymentChecks.map((project) => <article key={project.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-muted/60 p-4"><div><p className="font-extrabold">{project.name}</p><p className="mt-1 text-sm text-muted-foreground">Paid {formatINR(project.initialPayment!.amount)} · {project.initialPayment!.percentage}% of BOQ · UTR {project.initialPayment!.reference}</p>{project.initialPayment!.proofName && <p className="mt-1 text-xs text-muted-foreground">Proof selected: {project.initialPayment!.proofName} (upload activates with Firebase Storage)</p>}</div><button type="button" onClick={() => run(() => act.verifyInitialPayment(user!, project.id, true), "Payment verified", "Kurchi Admin has been notified and can now begin the project.")} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-extrabold text-primary-foreground"><CheckCircle2 className="h-4 w-4"/> Verify payment</button></article>)}</div></section>}
    {shipmentBilling.length > 0 && <section className="mt-7 rounded-3xl border bg-card p-5 sm:p-6"><div><p className="eyebrow">Shipment billing desk</p><h2 className="mt-1 text-xl font-extrabold">Ready to bill</h2><p className="mt-1 text-sm text-muted-foreground">Admin has completed the shipment checklist. Create the challan and GST invoice for this exact shipment in one step, then complete e-way bill details where required.</p></div><div className="mt-4 space-y-3">{shipmentBilling.map((shipment) => { const project = projects.find((entry) => entry.id === shipment.projectId); const invoice = shipment.invoiceId ? invoices.find((entry) => entry.id === shipment.invoiceId) : undefined; const client = project ? repo.clientById(project.clientId) : null; return <article key={shipment.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-muted/60 p-4"><div><p className="font-extrabold">{project?.site.city ?? "Showroom"}</p><p className="mt-1 text-sm text-muted-foreground">{shipment.boxCounts?.reduce((sum, count) => sum + count, 0) ?? 0} boxes · {formatINR(shipment.taxableValue)} · ETA {shipment.eta ? new Date(shipment.eta).toLocaleDateString("en-IN") : "calculating"}</p></div><div className="flex flex-wrap gap-2">{!invoice ? <button type="button" onClick={() => run(() => act.createShipmentBillingPack(user!, shipment.id), "GST invoice created", "The delivery challan was linked automatically. Complete e-way bill details before dispatch when required.")} className="min-h-10 rounded-xl bg-primary px-3 text-sm font-extrabold text-primary-foreground">Create GST invoice</button> : <><button type="button" onClick={() => printTaxInvoice(invoice, project, client)} className="min-h-10 rounded-xl border bg-background px-3 text-sm font-bold">Print invoice</button><Link to="/accounts/eway" className="inline-flex min-h-10 items-center rounded-xl border bg-background px-3 text-sm font-bold">E-way bill</Link><span className="inline-flex min-h-10 items-center rounded-xl bg-red-100 px-3 text-sm font-bold text-red-900">Invoice ready</span></>}</div></article>; })}</div></section>}
    <section className="mt-7"><p className="text-xs font-bold uppercase tracking-[.15em] text-primary">Start here</p><h2 className="mt-2 text-2xl font-extrabold">Choose what you need to do</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Action to="/accounts/cost-centres" title="Add project expense" description="Production, logistics, installation or site spend." Icon={WalletCards} /><Action to="/accounts/invoices" title="Invoice register" description="Review every invoice raised for a showroom." Icon={Receipt} /><Action to="/accounts/invoices" title="Create invoice" description="Prepare a GST tax invoice for the selected showroom." Icon={Receipt} /><Action to="/accounts/eway" title="Create e-way bill" description="Complete vehicle and movement details." Icon={FileText} /></div></section>
    <section className="mt-7 rounded-3xl border bg-card p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-primary">Money to follow up</p><h2 className="mt-2 text-xl font-extrabold">Collections overview</h2></div><IndianRupee className="h-6 w-6 text-primary" /></div><div className="mt-5 grid grid-cols-4 gap-2">{Object.entries(ageing).map(([period, amount]) => <div key={period} className="rounded-2xl bg-muted/60 p-3"><p className="text-xs font-bold text-muted-foreground">{period} days</p><p className="mt-2 text-sm font-extrabold">{formatCompactINR(amount)}</p></div>)}</div><Link to="/accounts/payments" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">Review payments <ArrowRight className="h-4 w-4" /></Link></section>
  </>;
}

function Metric({ label, value, note }: { label: string; value: string | number; note: string }) { return <div className="rounded-3xl border bg-card p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-3 text-2xl font-extrabold">{value}</p><p className="mt-2 text-xs text-muted-foreground">{note}</p></div>; }
function Action({ to, title, description, Icon }: { to: string; title: string; description: string; Icon: typeof FileText }) { return <Link to={to} className="group rounded-3xl border bg-card p-5 shadow-sm transition hover:border-primary/45 hover:shadow-md"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span><h3 className="mt-5 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{description}</p><ArrowRight className="mt-5 h-4 w-4 text-primary transition group-hover:translate-x-1" /></Link>; }
