import { Link } from "react-router-dom";
import { Building2, CheckCircle2, ChevronRight, ClipboardCheck, CreditCard, Timer } from "lucide-react";
import { useAuth } from "@/features/auth/AuthContext";
import { repo, openTickets } from "@/data/repo";
import { useDb } from "@/data/store";
import * as act from "@/data/actions";
import { useAction } from "@/lib/useAction";
import { EmptyState, PageHeader } from "@/components/app/Shell";
import type { OperationalStatus, Project } from "@/types";

const STAGES: Array<{ value: OperationalStatus; label: string; hint: string }> = [{ value: "ADVANCE_PENDING", label: "Advance pending", hint: "Waiting for planned advance" }, { value: "PRODUCTION", label: "In production", hint: "Making the showroom items" }, { value: "LOGISTICS", label: "In logistics", hint: "Packing and transport preparation" }, { value: "DELIVERED", label: "Delivered to site", hint: "Material received at location" }, { value: "INSTALLATION", label: "Installation", hint: "Installation team is working" }, { value: "COMPLETED", label: "Completed", hint: "Ready for accounts closure" }];
const stageOf = (p: Project) => p.operationalStatus ?? ((p.advanceReceivedPct ?? 0) < (p.advanceRequiredPct ?? 0) ? "ADVANCE_PENDING" : "PRODUCTION");
function timer(p: Project) { if (!p.deliveredToSiteAt || p.installationStartedAt) return null; const h = Math.ceil((new Date(p.deliveredToSiteAt).getTime() + 172800000 - Date.now()) / 3600000); return h <= 0 ? "48-hour start time missed" : `${h}h left to start installation`; }

export default function AdminDashboard() {
  useDb(); const { user } = useAuth(); const run = useAction(); const projects = repo.projects(user); const advances = projects.filter((p) => (p.advanceReceivedPct ?? 0) < (p.advanceRequiredPct ?? 0)); const late = projects.filter((p) => timer(p)?.includes("missed")); const tickets = openTickets(user); if (!user) return null;
  const olaRequests = projects.filter((p) => p.olaSubmittedAt && p.initialPayment?.status === "VERIFIED" && !p.adminAcceptedAt);
  const needsAttention = olaRequests[0] ?? late[0] ?? advances[0] ?? projects.find((p) => p.operationalStatus !== "COMPLETED") ?? projects[0];
  const isOlaRequest = Boolean(needsAttention?.olaSubmittedAt && !needsAttention?.adminAcceptedAt);
  const attentionText = needsAttention ? isOlaRequest ? "Accounts has verified Ola's payment. Check the showroom and franchisee details, then accept it to begin Kurchi work." : timer(needsAttention) ?? ((needsAttention.advanceReceivedPct ?? 0) < (needsAttention.advanceRequiredPct ?? 0) ? "Advance needs follow-up before work can move on." : `Currently ${STAGES.find((s) => s.value === stageOf(needsAttention))?.label.toLowerCase()}.`) : "Create your first showroom to begin.";
  return <><PageHeader eyebrow="Kurchi operations" title="Good morning. Here is what needs you." description="Ola submits a showroom first. Kurchi reviews it, prepares the BOQ, then manages the journey." actions={<Link to="/admin/projects" className="inline-flex min-h-11 items-center gap-2 rounded-xl border bg-card px-4 text-sm font-bold">All showrooms <ChevronRight className="h-4 w-4" /></Link>} />
  <section className="rounded-[2rem] bg-[linear-gradient(135deg,hsl(var(--primary)),hsl(350_58%_28%))] p-5 text-primary-foreground shadow-lg shadow-primary/10 sm:p-7"><p className="text-xs font-bold uppercase tracking-[.16em] text-primary-foreground/65">{isOlaRequest ? "New Ola request" : "Start here"}</p>{needsAttention ? <div className="mt-3 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-2xl font-extrabold sm:text-3xl">{needsAttention.name}</p><p className="mt-2 max-w-xl text-sm leading-relaxed text-primary-foreground/80">{attentionText}</p></div><div className="flex shrink-0 gap-2"><Link to={`/admin/projects/${needsAttention.id}`} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-white px-4 text-sm font-extrabold text-primary">View details</Link>{isOlaRequest && <button onClick={() => run(() => act.acceptOlaShowroom(user, needsAttention.id), "Showroom accepted", "You can now prepare the BOQ and assign the Kurchi team.")} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-white/15 px-4 text-sm font-bold hover:bg-white/20"><CheckCircle2 className="h-4 w-4" /> Accept showroom</button>}</div></div> : <div className="mt-4"><p className="text-lg font-bold">No showroom has been submitted by Ola yet.</p><p className="mt-2 text-sm text-primary-foreground/75">New locations will appear here for Kurchi review.</p></div>}</section>
  <section className="mt-4 grid gap-2 sm:grid-cols-3"><Link to="/admin/projects" className="flex items-center justify-between rounded-2xl border bg-card px-4 py-3 hover:border-primary/35"><span><b className="block text-lg">{projects.length}</b><span className="text-xs text-muted-foreground">active showrooms</span></span><ChevronRight className="h-4 w-4 text-muted-foreground"/></Link><Link to="/admin/projects" className="flex items-center justify-between rounded-2xl border bg-card px-4 py-3 hover:border-primary/35"><span><b className="block text-lg">{advances.length}</b><span className="text-xs text-muted-foreground">advance follow-ups</span></span><ChevronRight className="h-4 w-4 text-muted-foreground"/></Link><Link to="/admin/tickets" className="flex items-center justify-between rounded-2xl border bg-card px-4 py-3 hover:border-primary/35"><span><b className="block text-lg">{tickets.length}</b><span className="text-xs text-muted-foreground">site issues to review</span></span><ChevronRight className="h-4 w-4 text-muted-foreground"/></Link></section>
  <section className="mt-8"><div className="mb-3 flex items-end justify-between"><div><p className="eyebrow">Your showrooms</p><h2 className="text-xl font-extrabold">Keep work moving</h2></div><Link to="/admin/projects" className="text-sm font-bold text-primary">See all</Link></div>{projects.length === 0 ? <EmptyState title="No showrooms yet"/> : <div className="space-y-3">{projects.slice(0, 5).map((p) => { const stage = stageOf(p); return <article key={p.id} className="rounded-3xl border bg-card p-5 transition hover:border-primary/35"><div className="flex flex-wrap items-start justify-between gap-3"><Link to={`/admin/projects/${p.id}`} className="group"><h3 className="text-xl font-extrabold group-hover:text-primary">{p.site.city}</h3><p className="mt-1 text-sm text-muted-foreground">{p.code} · {p.site.contactName}</p></Link><Link to={`/admin/projects/${p.id}`} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-primary-foreground">View details <ChevronRight className="h-4 w-4"/></Link></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><Info label="Now" value={STAGES.find((s) => s.value === stage)?.label ?? stage}/><Info label="Advance" value={`${p.advanceReceivedPct ?? 0}% received`}/><Info label="Next" value={p.operationalExpectedDate ? new Date(p.operationalExpectedDate).toLocaleDateString("en-IN", { day: "numeric", month: "short" }) : "Add expected date"}/></div>{timer(p) && <p className="mt-3 flex items-center gap-1.5 text-sm font-bold text-amber-700"><Timer className="h-4 w-4"/>{timer(p)}</p>}</article>; })}</div>}</section>
  <section className="mt-7 grid gap-2 sm:grid-cols-3"><Link to="/admin/franchisees" className="group flex items-center justify-between rounded-2xl bg-muted/70 p-4"><span><b className="block">Add franchisee</b><span className="text-sm text-muted-foreground">Owner and showroom location</span></span><Building2 className="h-5 w-5 text-primary"/></Link><Link to="/admin/projects" className="group flex items-center justify-between rounded-2xl bg-muted/70 p-4"><span><b className="block">Prepare a BOQ</b><span className="text-sm text-muted-foreground">Review showroom scope</span></span><ClipboardCheck className="h-5 w-5 text-primary"/></Link><Link to="/admin/cost-centres" className="group flex items-center justify-between rounded-2xl bg-muted/70 p-4"><span><b className="block">Add project cost</b><span className="text-sm text-muted-foreground">Production, logistics or site</span></span><CreditCard className="h-5 w-5 text-primary"/></Link></section>
  </>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-muted/60 p-3"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1.5 text-sm font-bold">{value}</p></div>; }
