import { useState } from "react";
import { Check, ClipboardCheck, RotateCcw } from "lucide-react";
import { useAuth } from "@/features/auth/AuthContext";
import { repo } from "@/data/repo";
import { useDb } from "@/data/store";
import * as act from "@/data/actions";
import { useAction } from "@/lib/useAction";
import { EmptyState } from "@/components/app/Shell";
import { formatINR } from "@/lib/money";

export default function ApprovalsPage() {
  useDb(); const { user } = useAuth(); const run = useAction(); const [open, setOpen] = useState<string | null>(null); const [note, setNote] = useState("");
  if (!user) return null;
  const projects = repo.projects(user); const waiting = projects.filter((p) => p.status === "PENDING_APPROVAL");
  return <><section className="mb-7 rounded-[2rem] bg-rail p-6 text-rail-foreground sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-rail-muted">Ola decisions</p><h1 className="mt-3 text-3xl font-extrabold">Only review what needs your answer.</h1><p className="mt-2 text-sm text-rail-muted">Approve a showroom scope when it looks right, or send it back with one clear note.</p></section>
    {waiting.length === 0 ? <EmptyState title="You are all caught up" hint="New BOQ approvals will appear here when Kurchi sends them." /> : <div className="space-y-4">{waiting.map((project) => { const items = repo.items(project.id, user.role); const total = items.reduce((sum, item) => sum + (item.finalPrice ?? 0) * item.qty, 0); return <article key={project.id} className="rounded-3xl border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-primary">Showroom scope</p><h2 className="mt-2 text-2xl font-extrabold">{project.site.city}</h2><p className="mt-1 text-sm text-muted-foreground">{items.length} items · {formatINR(total)}</p></div><span className="rounded-full bg-amber-100 px-3 py-1.5 text-xs font-bold text-amber-900">Needs your decision</span></div><div className="mt-5 rounded-2xl bg-muted/55 p-4"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Included</p><p className="mt-2 text-sm font-semibold">{items.slice(0, 3).map((item) => `${item.name} ×${item.qty}`).join(" · ")}{items.length > 3 ? ` · +${items.length - 3} more` : ""}</p></div><div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={() => run(() => act.approveBoq(user, project.id), "BOQ approved", "Kurchi can now prepare the showroom.")} className="inline-flex min-h-12 items-center gap-2 rounded-2xl bg-primary px-5 text-sm font-extrabold text-primary-foreground"><Check className="h-4 w-4" /> Approve BOQ</button><button type="button" onClick={() => { setOpen(open === project.id ? null : project.id); setNote(""); }} className="inline-flex min-h-12 items-center gap-2 rounded-2xl border px-5 text-sm font-bold"><RotateCcw className="h-4 w-4" /> Ask for changes</button></div>{open === project.id && <div className="mt-4 rounded-2xl border bg-muted/30 p-4"><label className="text-sm font-bold">What should Kurchi change?</label><textarea value={note} onChange={(event) => setNote(event.target.value)} rows={3} placeholder="Tell us simply what needs to change." className="mt-2 w-full rounded-xl border bg-background p-3 text-sm"/><button type="button" disabled={note.trim().length < 5} onClick={() => { const done = run(() => act.rejectBoq(user, project.id, note.trim()), "Sent back to Kurchi"); if (done) setOpen(null); }} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-xl bg-foreground px-4 text-sm font-bold text-background disabled:opacity-40"><ClipboardCheck className="h-4 w-4" /> Send request</button></div>}</article>; })}</div>}
  </>;
}
