import { useState } from "react";
import { ArrowLeft, Building2, CheckCircle2, Store, UserRound } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "@/features/auth/AuthContext";
import { repo } from "@/data/repo";
import * as act from "@/data/actions";
import { useAction } from "@/lib/useAction";

const STATES = ["Andhra Pradesh", "Assam", "Bihar", "Chhattisgarh", "Delhi", "Goa", "Gujarat", "Haryana", "Karnataka", "Kerala", "Maharashtra", "Tamil Nadu", "Telangana", "Uttar Pradesh", "West Bengal"];

/** A deliberately small intake: Ola gives Kurchi the location and partner; Kurchi handles BOQ and operations afterwards. */
export default function NewShowroomRequestPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const run = useAction();
  const client = repo.clients().find((row) => row.id === user?.clientId) ?? repo.clients()[0];
  const programme = repo.programmes().find((row) => row.clientId === client?.id);
  const [showroomName, setShowroomName] = useState(""); const [city, setCity] = useState(""); const [state, setState] = useState("Karnataka"); const [pincode, setPincode] = useState(""); const [address, setAddress] = useState(""); const [gstin, setGstin] = useState(""); const [owner, setOwner] = useState(""); const [phone, setPhone] = useState(""); const [email, setEmail] = useState(""); const [openingDate, setOpeningDate] = useState("");
  if (!user || !client) return null;
  const ready = showroomName.trim() && city.trim() && address.trim() && pincode.length === 6 && owner.trim() && phone.trim() && openingDate;
  const submit = () => run(() => {
    const project = act.createProjectFromKit(user, { clientId: client.id, programmeId: programme?.id ?? "", showroomName, showroomGstin: gstin, city, state, pincode, address, contactName: owner, contactPhone: phone, targetCompletionDate: openingDate, retentionPct: 5, dlpMonths: 12, quantities: {}, franchisee: { name: owner, phone, email, gstin } });
    navigate(`/portal/projects/${project.id}`);
  }, "Showroom sent to Kurchi", "Kurchi Admin will check the details and begin BOQ preparation.");
  return <div className="mx-auto max-w-3xl"><Link to="/portal" className="mb-5 inline-flex items-center gap-1.5 text-sm font-bold text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Back to showrooms</Link>
    <section className="rounded-[2rem] bg-rail p-6 text-rail-foreground sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-rail-muted">Ola rollout</p><h1 className="mt-3 text-3xl font-extrabold">Add a new showroom</h1><p className="mt-2 max-w-xl text-sm leading-relaxed text-rail-muted">Share the showroom and franchisee details. Kurchi will check the request, prepare the BOQ, then start the work.</p><div className="mt-5 flex items-center gap-2 text-xs font-bold text-rail-muted"><CheckCircle2 className="h-4 w-4 text-primary" /> Your request goes to Kurchi Admin for approval.</div></section>
    <section className="mt-5 space-y-5"><FormCard icon={<Store className="h-5 w-5"/>} title="Showroom details" hint="This is the location Kurchi will build."><div className="grid gap-3 sm:grid-cols-2"><Field label="Showroom name" value={showroomName} onChange={setShowroomName} placeholder="Ola Electric — Indiranagar" required/><Field label="City" value={city} onChange={setCity} placeholder="Bengaluru" required/><Select label="State" value={state} onChange={setState} options={STATES}/><Field label="PIN code" value={pincode} onChange={(value) => setPincode(value.replace(/\D/g, "").slice(0, 6))} placeholder="560038" required/><div className="sm:col-span-2"><Field label="Full showroom address" value={address} onChange={setAddress} placeholder="Building, road, area and landmark" required/></div><Field label="Showroom GSTIN" value={gstin} onChange={(value) => setGstin(value.toUpperCase())} placeholder="Optional, if already available"/><Field label="Expected opening date" type="date" value={openingDate} onChange={setOpeningDate} required/></div></FormCard>
      <FormCard icon={<UserRound className="h-5 w-5"/>} title="Franchisee owner" hint="This owner will receive the BOQ for selection and approval."><div className="grid gap-3 sm:grid-cols-2"><Field label="Owner name" value={owner} onChange={setOwner} placeholder="Full name" required/><Field label="Mobile number" value={phone} onChange={setPhone} placeholder="+91 98XXX XXXXX" required/><div className="sm:col-span-2"><Field label="Email address" type="email" value={email} onChange={setEmail} placeholder="For welcome invite — optional for now"/></div></div></FormCard>
      <button disabled={!ready} onClick={submit} className="inline-flex min-h-13 w-full items-center justify-center rounded-2xl bg-primary px-5 text-sm font-extrabold text-primary-foreground disabled:cursor-not-allowed disabled:opacity-40">Send showroom to Kurchi for review</button>{!ready && <p className="text-center text-xs text-muted-foreground">Complete the required showroom and franchisee details to continue.</p>}</section></div>;
}

function FormCard({ icon, title, hint, children }: { icon: React.ReactNode; title: string; hint: string; children: React.ReactNode }) { return <article className="rounded-3xl border bg-card p-5 shadow-sm sm:p-6"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-primary/10 text-primary">{icon}</span><div><h2 className="font-extrabold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{hint}</p></div></div><div className="mt-5">{children}</div></article>; }
function Field({ label, value, onChange, placeholder, required, type = "text" }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; required?: boolean; type?: string }) { return <label className="block text-sm font-bold">{label}{required && <span className="ml-1 text-primary">*</span>}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-1.5 min-h-12 w-full rounded-xl border bg-background px-3 text-sm font-medium placeholder:font-normal placeholder:text-muted-foreground" /></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="block text-sm font-bold">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 min-h-12 w-full rounded-xl border bg-background px-3 text-sm font-medium">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
